name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Configurar Node.js para pruebas con Cypress
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # 3. Instalar dependencias de Node.js
    - name: Install dependencies
      run: npm install

    # 4. Ejecutar las pruebas de Cypress
    - name: Run Cypress tests
      run: npm run cypress:run

    # 5. Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 6. Configurar Docker Buildx para construir imágenes
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 7. Construir y publicar la imagen Docker
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: newyork360/testinganddata:latest
